### ISSUE TITLE
Please consider handling BOOLEAN data type

### ISSUE THREAD

**Issue by ParensAllTheWayDown** [narendrans/dremio-snowflake#13]
**What would you like to be added**:

```
CREATE OR REPLACE TABLE PROD_TEMP.TEMP.booleantest (iscool boolean)
```

```
2019-08-13 20:00:55,163 [22ace908-d877-e0ab-fa46-de0ece93fd00/0:foreman-planning] WARN  c.d.e.store.jdbc.dialect.TypeMapper - A column you queried has a data type that is not currently supported by the JDBC storage plugin. The column's name was PROD_TEMP.TEMP.BOOLEANTEST.ISCOOL,
 its JDBC data type was BOOLEAN, and the source column type was BOOLEAN.
2019-08-13 20:00:55,165 [22ace908-d877-e0ab-fa46-de0ece93fd00/0:foreman-planning] INFO  c.d.e.store.jdbc.JdbcDatasetMetadata - Took 336 ms to get column metadata for [sf-dremio, PROD_TEMP, TEMP, BOOLEANTEST]
...
2019-08-13 20:00:55,610 [22ace908-d877-e0ab-fa46-de0ece93fd00/0:foreman-planning] INFO  com.dremio.exec.record.BatchSchema - User Error Occurred [ErrorId: 88568829-c2e7-4181-8145-bef98e6e1c0b]
com.dremio.common.exceptions.UserException: Selected table has no columns.
        at com.dremio.common.exceptions.UserException$Builder.build(UserException.java:773) ~[dremio-common-3.2.4-201906051751050278-1bcce62.jar:3.2.4-201906051751050278-1bcce62]
        at com.dremio.exec.record.BatchSchema.toCalciteRecordType(BatchSchema.java:232) [dremio-sabot-kernel-3.2.4-201906051751050278-1bcce62.jar:3.2.4-201906051751050278-1bcce62]
        at com.dremio.exec.store.NamespaceTable.getRowType(NamespaceTable.java:66) [dremio-sabot-kernel-3.2.4-201906051751050278-1bcce62.jar:3.2.4-201906051751050278-1bcce62]

```

**Why is this needed**:
boolean column type is used in some cases in production environment.

**Comment by narendrans** [comment]
Merged PR #14, Thanks!
