### ISSUE TITLE
DQL issue in AWS CFT v 13.2

### ISSUE THREAD

**Issue by piyushma** [narendrans/dremio-snowflake#36]
**What happened**: DQLs are failing

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**: 
1. Install Dremio from AWS marketplace (we tried v13.2)
2. Install the plugin
3. Connect to underlying Snowflake
4. Query editor run DQL

**Anything else we need to know?**: We tried this in Dremio v12 standalone version and it works

**Details**:
- Dremio version (Help > About from the UI):13.2 (from AWS Marketplace)
- Profile zip:
- server.log:
2021-03-02 10:41:45,498 [grpc-default-executor-2] INFO  c.d.service.jobs.JobResultsStore - User Error Occurred [ErrorId: d9a52e9b-808f-47d3-aaa8-32fca069ebd8]
com.dremio.common.exceptions.UserException: Failure getting source
        at com.dremio.common.exceptions.UserException$Builder.build(UserException.java:804)
        at com.dremio.service.jobs.JobResultsStore.loadJobData(JobResultsStore.java:145)
        at com.dremio.service.jobs.JobResultsStore$LateJobLoader.load(JobResultsStore.java:294)
        at com.dremio.service.jobs.JobDataImpl.range(JobDataImpl.java:46)
        at com.dremio.service.jobs.LocalJobsService.getJobData(LocalJobsService.java:906)
        at com.dremio.service.jobs.JobsFlightProducer.getStream(JobsFlightProducer.java:76)
        at org.apache.arrow.flight.FlightService.doGetCustom(FlightService.java:111)
        at org.apache.arrow.flight.FlightBindingService$DoGetMethod.invoke(FlightBindingService.java:144)
        at org.apache.arrow.flight.FlightBindingService$DoGetMethod.invoke(FlightBindingService.java:134)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)

**Comment by narendrans** [comment]
doesn't look like an issue related to the connector plugin.. if you have more info on how to reproduce please let me know and reopen this issue.
