### ISSUE TITLE
Dremio services fails to start after upgrading to v23.0.1 snowflake connector

### ISSUE THREAD

**Issue by sukumarbairi** [narendrans/dremio-snowflake#46]
@narendrans 

**What happened**:
Dremio services fails to start after upgrading to v23.0.1 and rebuilding the snowflake connectors to v23.0.1

**What you expected to happen**:
It should be working fine after upgrading both dremio version and snowflake connectors to v23.0.1

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade Dremio to v23.0.1 and update the connectors to v23.0.1, restart dremio coordinators, executors.

**Anything else we need to know?**:
Error from server.log
2022-12-19 07:25:59,456 [main] ERROR ROOT - Dremio is exiting. Failure while starting services.
java.lang.RuntimeException: Reading from a byte array threw an IOException (should never happen).
        at io.protostuff.IOUtil.mergeFrom(IOUtil.java:54)
        at io.protostuff.ProtobufIOUtil.mergeFrom(ProtobufIOUtil.java:103)
        at com.dremio.exec.catalog.ConnectionReaderImpl.getConnectionConf(ConnectionReaderImpl.java:118)
        at com.dremio.exec.catalog.ConnectionReaderImpl.getConnectionConf(ConnectionReaderImpl.java:125)
        at com.dremio.exec.catalog.ManagedStoragePlugin.<init>(ManagedStoragePlugin.java:173)
        at com.dremio.exec.catalog.EnterpriseManagedStoragePlugin.<init>(EnterpriseManagedStoragePlugin.java:64)
        at com.dremio.exec.catalog.EnterprisePluginsManager.newManagedStoragePlugin(EnterprisePluginsManager.java:69)
        at com.dremio.exec.catalog.PluginsManager.newPlugin(PluginsManager.java:280)
        at com.dremio.exec.catalog.PluginsManager.start(PluginsManager.java:224)
        at com.dremio.exec.catalog.CatalogServiceImpl.start(CatalogServiceImpl.java:216)
        at com.dremio.service.SingletonRegistry$AbstractServiceReference.start(SingletonRegistry.java:139)
        at com.dremio.service.ServiceRegistry.start(ServiceRegistry.java:88)
        at com.dremio.service.SingletonRegistry.start(SingletonRegistry.java:33)
        at com.dremio.dac.daemon.DACDaemon.startServices(DACDaemon.java:199)
        at com.dremio.dac.daemon.DACDaemon.init(DACDaemon.java:205)
        at com.dremio.dac.daemon.DremioDaemon.main(DremioDaemon.java:104)
        Suppressed: java.lang.NullPointerException: null
                at com.dremio.service.orphanagecleaner.OrphanageCleanerService.close(OrphanageCleanerService.java:124)
                at com.dremio.service.SingletonRegistry$AbstractServiceReference.close(SingletonRegistry.java:132)
                at com.dremio.common.AutoCloseables.close(AutoCloseables.java:139)
                at com.dremio.service.ServiceRegistry.close(ServiceRegistry.java:96)
                at com.dremio.service.SingletonRegistry.close(SingletonRegistry.java:90)
                at com.dremio.common.AutoCloseables.close(AutoCloseables.java:139)
                at com.dremio.common.AutoCloseables.close(AutoCloseables.java:76)
                at com.dremio.dac.daemon.DACDaemon.close(DACDaemon.java:299)
                at com.dremio.dac.daemon.DremioDaemon.main(DremioDaemon.java:103)
                Suppressed: java.lang.NullPointerException: null
                        at com.dremio.provision.service.ProvisioningServiceImpl.close(ProvisioningServiceImpl.java:512)
                        ... 8 common frames omitted
Caused by: io.protostuff.ProtobufException: CodedInput encountered an embedded string or bytes that misreported its size.
        at io.protostuff.ProtobufException.misreportedSize(ProtobufException.java:86)
        at io.protostuff.ByteArrayInput.readString(ByteArrayInput.java:438)
        at io.protostuff.runtime.RuntimeUnsafeFieldFactory$9$1.mergeFrom(RuntimeUnsafeFieldFactory.java:753)
        at io.protostuff.runtime.RuntimeSchema.mergeFrom(RuntimeSchema.java:463)
        at io.protostuff.CustomSchema.mergeFrom(CustomSchema.java:57)
        at io.protostuff.IOUtil.mergeFrom(IOUtil.java:45)
        ... 15 common frames omitted

**Details**:
- Dremio version (Help > About from the UI): 23.0.1-202210141019030815-c1de8bcc
- Profile zip: 
- server.log: 
[server.log](https://github.com/narendrans/dremio-snowflake/files/10256946/server.log)

**Comment by sukumarbairi** [comment]
I was able to fix the issue by

1.  Removing the snowflake datasource
2. Remove the snowflake plugin and jdbc jar
3. Upgrade the cluster
4. Deploy v23.0.1 plugin jar and all the nodes in the cluster
5. Restart Dremio service on all the cluster nodes
6. Recreate snowflake datasource
